---
# Source: metricbeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-metricbeat
  annotations:
  labels:
    app: "metricbeat-metricbeat"
    chart: "metricbeat-7.16.2"
    heritage: "Helm"
    release: "metricbeat"
